/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_simulation;

import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author bahgat
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        DV1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DV2 = new javax.swing.JTextField();
        DV3 = new javax.swing.JTextField();
        DV4 = new javax.swing.JTextField();
        DV5 = new javax.swing.JTextField();
        DV6 = new javax.swing.JTextField();
        DF1 = new javax.swing.JTextField();
        DF2 = new javax.swing.JTextField();
        DF3 = new javax.swing.JTextField();
        DF4 = new javax.swing.JTextField();
        DF5 = new javax.swing.JTextField();
        DF6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Daily demand", "frequency", "Probability", "Commulative", "Start Interval", "End Interval", "Expected Daily Demand", "Day", "Random Numbers", "SIMULATED DAILY DEMAND"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jButton3.setText("Run");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        DV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DV1ActionPerformed(evt);
            }
        });

        jLabel2.setText("value1");

        jLabel3.setText("value2");

        jLabel4.setText("value3");

        jLabel5.setText("value4");

        jLabel6.setText("vaLue5");

        jLabel7.setText("value6");

        DV6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DV6ActionPerformed(evt);
            }
        });

        DF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DF1ActionPerformed(evt);
            }
        });

        DF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DF2ActionPerformed(evt);
            }
        });

        DF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DF3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Daily demand");

        jLabel9.setText("Frequency");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DV1)
                                    .addComponent(DV2)
                                    .addComponent(DV3)
                                    .addComponent(DV4)
                                    .addComponent(DV5)
                                    .addComponent(DV6, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DF1)
                                    .addComponent(DF2)
                                    .addComponent(DF3)
                                    .addComponent(DF4)
                                    .addComponent(DF5)
                                    .addComponent(DF6, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                                .addGap(78, 78, 78)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 122, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(DV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(DV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(DV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(DV6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      DecimalFormat numberFormat = new DecimalFormat("#0.00");
        int [] v=new int[6]; 
      v[0]=Integer.parseInt(DV1.getText());
      v[1]=Integer.parseInt(DV2.getText());
      v[2]=Integer.parseInt(DV3.getText());
      v[3]=Integer.parseInt(DV4.getText());
      v[4]=Integer.parseInt(DV5.getText());
      v[5]=Integer.parseInt(DV6.getText());
      int [] f=new int [6];
      f[0]=Integer.parseInt(DF1.getText());
      f[1]=Integer.parseInt(DF2.getText());
      f[2]=Integer.parseInt(DF3.getText());
      f[3]=Integer.parseInt(DF4.getText());
      f[4]=Integer.parseInt(DF5.getText());
      f[5]=Integer.parseInt(DF6.getText());
      float sum=(f[0]+f[1]+f[2]+f[3]+f[4]+f[5]);
      float [] fp=new float[6];
      fp[0]=f[0]/sum;
      fp[1]=f[1]/sum;
      fp[2]=f[2]/sum;
      fp[3]=f[3]/sum;
      fp[4]=f[4]/sum;
      fp[5]=f[5]/sum;
      int i=0;
      float [] c=new float[6];
      c[0]=0;
      for(;i<=5;i++){
          if(i==0){
        c[i]=fp[i];}
          else{  
        c[i]=c[i-1]+fp[i];  
      
          }
      }
      int s=0;
      float [] interv=new float[6];
      for(;s<6;s++){
        interv[s]=(c[s]*100.0f);
      }
      int [] rand={52,37,82,69,98,96,33,50,88,90};
      int x=0,y;
      float p=0;
      int [] Sim=new int[10];
      for(;x<10;x++){
          for(y=0;y<5;y++){
          if(rand[x]>=1 && rand[x]<=5){
              Sim[x]=0;
              break;
          }
          else if(rand[x]>=interv[y]+1 && rand[x]<=interv[y+1]){
              Sim[x]=y+1;
              break;
          }
        }
         p+=Sim[x];
      }
      float Result=p/10;
      int z=0;
      float total=0;
      for(;z<=5;z++){
        
          total+=fp[z]*z;
      }
      float [] Sinterv=new float[6];
      Sinterv[0]=1;
      for(int n=1;n<6;n++){
       Sinterv[n]=interv[n-1]+1;
      }
      DefaultTableModel M=(DefaultTableModel)jTable2.getModel();
      Object[]row = new Object[14];
       
       for ( i = 0; i <10; i++) {
           if(i<6){
           row[0]=v[i];
           row[1]=f[i];
           row[2]=numberFormat.format(fp[i]);
           row[3]=numberFormat.format(c[i]);
           row[4]=numberFormat.format(Sinterv[i]);
           row[5]=numberFormat.format(interv[i]);
           row[6]=numberFormat.format(fp[i]*i);
           row[7]=i+1;
           row[8]=rand[i];
           row[9]=Sim[i];
           M.addRow(row);
       }
           else{
           row[0]=null;
           row[1]=null;
           row[2]=null;
           row[3]=null;
           row[4]=null;
           row[5]=null;
           row[6]=null;
           row[7]=i+1;
           row[8]=rand[i];
           row[9]=Sim[i];
           M.addRow(row);
           }

       }
           row[0]=null;
           row[1]=null;
           row[2]=null;
           row[3]=null;
           row[4]=null;
           row[5]="Expected";
           row[6]=total;
           row[7]=null;
           row[8]="Result";
           row[9]=Result;
           M.addRow(row);
           
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void DV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DV1ActionPerformed

    private void DV6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DV6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DV6ActionPerformed

    private void DF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DF1ActionPerformed

    private void DF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DF2ActionPerformed

    private void DF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DF3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DF1;
    private javax.swing.JTextField DF2;
    private javax.swing.JTextField DF3;
    private javax.swing.JTextField DF4;
    private javax.swing.JTextField DF5;
    private javax.swing.JTextField DF6;
    private javax.swing.JTextField DV1;
    private javax.swing.JTextField DV2;
    private javax.swing.JTextField DV3;
    private javax.swing.JTextField DV4;
    private javax.swing.JTextField DV5;
    private javax.swing.JTextField DV6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
